release:
  name_template: "{{.ProjectName}} v{{.Version}}"

builds:
  -
    main: .
    id: "cli"
    binary: goalconvert-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
      - netbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - riscv64
    goarm:
      - 5
      - 6
      - 7
archives:
  -
    replacements:
      amd64: 64bit
      386: 32bit
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'

